---
name: Run YAMLsmith Training Script
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
jobs:
  training:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install

      - name: Fetch training models
        run: |
          # Ensure the required tools are installed
          if ! command -v git &> /dev/null; then
            echo "Git is not installed. Installing Git..."
            sudo apt-get update && sudo apt-get install -y git
          fi

          # Create the model directory if it doesn't exist
          mkdir -p model
          cd model

          # Disable Git clone protection
          export GIT_CLONE_PROTECTION_ACTIVE=false

          # Clone the repository, with error handling
          REPO_URL="https://huggingface.co/liangwen12year/training"
          if git clone "$REPO_URL"; then
            echo "Repository cloned successfully."
          else
            echo "Failed to clone the repository from $REPO_URL"
            exit 1
          fi

      - name: List training models
        run: ls -lh model/training/

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install transformers[torch] argparse datasets numpy pyyaml

      - name: Run training script
        run: |
          python src/train.py --model_path model/training/ --data_path dataset/training/training.yaml
